services:
  db:
    container_name: postgres
    image: postgres:13.22
    environment:
      POSTGRES_USER: joelsng
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  # redis:
  #   image: redis:8.2
  #   ports:
  #   - "6379:6379"

  # frontend:
  #   build: ./frontend
  #   depends_on:
  #     - "backend"
  #   ports:
  #     - "3000:3000"

  backend:
    build: ./backend
    depends_on:
      - db
      # - redis
    ports:
      - "8080:8080"

volumes:
  db: