###
POST http://localhost:8080/api/auth/signin
Content-Type: application/json

{
  "username": "testuser2",
  "password": "password1234"
}

###
GET http://localhost:8080/api/test/admin

### Upload PDF to FastAPI
POST http://localhost:8000/document
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.pdf"
Content-Type: application/pdf

< ./test.pdf
--WebAppBoundary
Content-Disposition: form-data; name="jobId"

test-123
--WebAppBoundary--

### Upload PDF to Spring to FastAPI
POST http://localhost:8080/api/documents/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.pdf"
Content-Type: application/pdf

< ./test.pdf
--WebAppBoundary--

### Test /extract (IntelliJ HTTP Client)
POST http://localhost:8000/extract
Content-Type: application/json

{
  "jobId": "job-123",
  "text": ["Page 1 text. Joel's Age is 24. He is extremely cunning.", "Page 2 text. Joel's hair colour is red."],
  "fields": { "Age": "", "Species": "", "Type": "How cunning is Joel?" }
}

### Test /extract (IntelliJ HTTP Client)
POST http://localhost:8080/api/extraction/extract
Content-Type: application/json

{
  "jobId": "job-123",
  "text": ["Page 1 text. Joel's Age is 24. He is extremely cunning.", "Page 2 text. Joel's hair colour is red."],
  "fields": { "Age": "", "Species": "", "Type": "How cunning is Joel?" }
}